In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([

In [9]:
path="data.csv"

In [12]:
df=pd.read_csv(path,sep=",")

/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [13]:
df.head()

label                        window
0    854  115349,21589,1024,141917,854
1  14658  115349,21589,1024,141917,854
2    854     21589,1024,141917,854,854
3  14658     21589,1024,141917,854,854
4  94828       1024,141917,854,854,854

In [14]:
def map_str(features):
    print(features)
    return [int(v) for v in features.split(",") ]

def tf_serialize_example(f0):
    label = f0["label"]
    feature = f0["window"]
    return label,tf.strings.to_number(tf.sparse.to_dense(tf.strings.split(feature,sep=","),default_value="0"),out_type=tf.int64 )

In [15]:
dataset= tf.data.experimental.make_csv_dataset(path,batch_size=1).map(lambda x:tf_serialize_example(x))

Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
Instructions for updating:
Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.


In [18]:
iterator = dataset.make_one_shot_iterator()
elem = iterator.get_next()
with tf.Session() as sess:
    for i in range(10):
        _elem = sess.run(elem)
        print(_elem)

(array([988], dtype=int32), array([[ 37637, 103077,    988,  20787,   3464]]))
(array([5486], dtype=int32), array([[18, 18, 18, 18, 18]]))
(array([42], dtype=int32), array([[32312,  7497,  4577, 26016,    87]]))
(array([118569], dtype=int32), array([[    54,     54,    549,    549, 118569]]))
(array([22108], dtype=int32), array([[22108, 22108, 22108, 22108, 22108]]))
(array([6597], dtype=int32), array([[51801, 11501,  5753, 20172, 32769]]))
(array([9], dtype=int32), array([[2598, 2598, 2598, 2598, 2598]]))
(array([2806], dtype=int32), array([[2806, 2806, 2806, 2806, 2806]]))
(array([7726], dtype=int32), array([[ 7726,  7726,   974,  7726, 43385]]))
(array([8098], dtype=int32), array([[129482,    202,    202, 173928, 173928]]))
