In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/songfeng/APP/env/python/anaconda3/envs/tensorflow14/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([

In [2]:
df = pd.read_csv("../data/test_data2.csv")

In [3]:
df.head()

label_name                      features
0         854  115349,21589,1024,141917,854
1       14658  115349,21589,1024,141917,854
2         854     21589,1024,141917,854,854
3       14658     21589,1024,141917,854,854
4       94828       1024,141917,854,854,854

In [30]:
def map_str(features):
    print(features)
    return [int(v) for v in features.split(",") ]

def tf_serialize_example(f0):
    label = f0["label_name"]
    feature = f0["features"]
    return label,tf.strings.to_number(tf.sparse.to_dense(tf.strings.split(feature,sep=","),default_value="0"),out_type=tf.int64 )

In [31]:
dataset= tf.data.experimental.make_csv_dataset("../data/test_data2.csv",batch_size=1).map(lambda x:tf_serialize_example(x))

In [38]:
i = 0
for v in dataset.take(1):
    if i > 5:
        break
    i+=1
    print(v)

(<tf.Tensor 'IteratorGetNext_44:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_44:1' shape=(?, ?) dtype=int64>)
(<tf.Tensor 'IteratorGetNext_45:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_45:1' shape=(?, ?) dtype=int64>)
(<tf.Tensor 'IteratorGetNext_46:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_46:1' shape=(?, ?) dtype=int64>)
(<tf.Tensor 'IteratorGetNext_47:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_47:1' shape=(?, ?) dtype=int64>)
(<tf.Tensor 'IteratorGetNext_48:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_48:1' shape=(?, ?) dtype=int64>)
(<tf.Tensor 'IteratorGetNext_49:0' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext_49:1' shape=(?, ?) dtype=int64>)


In [48]:
iterator = dataset.make_one_shot_iterator()
elem = iterator.get_next()
with tf.Session() as sess:
    for i in range(10):
        _elem = sess.run(elem)
        print(_elem)

(array([103109], dtype=int32), array([[ 74591, 438194, 186776,  48975,  26238]]))
(array([72250], dtype=int32), array([[72250, 72250, 72250, 72250, 72250]]))
(array([45101], dtype=int32), array([[ 17383,   9451, 159865,  39793,  35100]]))
(array([82933], dtype=int32), array([[  257, 21754, 21754,  5836,  5836]]))
(array([9], dtype=int32), array([[9, 9, 9, 9, 9]]))
(array([26284], dtype=int32), array([[75523,  9590, 16332, 26284, 26284]]))
(array([33372], dtype=int32), array([[33372, 33372, 33372, 33372, 33372]]))
(array([77219], dtype=int32), array([[412110,  77219,  77219,  77219,  77219]]))
(array([4910], dtype=int32), array([[401485, 429995, 347794, 426422, 464009]]))
(array([488], dtype=int32), array([[5393, 5393,  165,  165,  165]]))


In [53]:
df[df["features"]=="72250,72250,72250,72250,72250"]

label_name                       features
8984       72250  72250,72250,72250,72250,72250
8985       72250  72250,72250,72250,72250,72250
8986       72250  72250,72250,72250,72250,72250
8987       72250  72250,72250,72250,72250,72250
8988       72250  72250,72250,72250,72250,72250
8989       72250  72250,72250,72250,72250,72250
8990       72250  72250,72250,72250,72250,72250
8991       72250  72250,72250,72250,72250,72250

In [54]:
807526948 + 971215059

1778742007

In [55]:
1778742007 % 1000000007

778742000